version: '3.8'

services:

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #
  #   Support Services
  #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  minio:
    image: minio/minio
    command: server --console-address ':9001' /data
    ports:
    - "9000:9000"
    - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${COMPUTE_S3_ACCESS_TOKEN}
      MINIO_ROOT_PASSWORD: ${COMPUTE_S3_SECRET_KEY}

  minio-create-buckets:
    image: minio/mc
    depends_on:
    - minio
    environment:
      MINIO_USER: ${COMPUTE_S3_ACCESS_TOKEN}
      MINIO_PASS: ${COMPUTE_S3_SECRET_KEY}
      MINIO_BUCKET: ${COMPUTE_S3_BUCKET}
    entrypoint: >
      /bin/sh -c "
      sleep 1;
      /usr/bin/mc alias set minioc http://minio:9000 ${MINIO_USER} ${MINIO_PASS};
      /usr/bin/mc mb minioc/${MINIO_BUCKET};
      /usr/bin/mc policy set public minioc/${MINIO_BUCKET};
      exit 0;
      "

  compute-queue-db:
    image: postgres:14.3-alpine3.16
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: ${COMPUTE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${COMPUTE_POSTGRES_PASS}
      POSTGRES_DB: ${COMPUTE_POSTGRES_DB}

  compute-queue:
    image: rabbitmq:3.10.5-management-alpine
    ports:
    - "9002:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${COMPUTE_QUEUE_USER}
      RABBITMQ_DEFAULT_PASS: ${COMPUTE_QUEUE_PASS}

  rserve:
    image: veupathdb/rserve:${RSERVE_TAG:-latest}

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #
  #   EDA Services
  #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

  eda-subsetting:
    image: veupathdb/eda-subsetting:${SUBSETTING_TAG:-latest}
    environment:
      # port providing the service
      SERVER_PORT: ${SUBSETTING_SERVER_PORT:-8080}

      # URLs of required services
      DATASET_ACCESS_SERVICE_URL: ${DATASET_ACCESS_SERVICE_URL:-http://dataset-access}:${DATASET_ACCESS_SERVER_PORT:-8080}

      # LDAP values to look up DBs
      LDAP_SERVER: ${LDAP_SERVER}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN}

      # Application Database
      APP_DB_TNS_NAME: ${APP_DB_TNS_NAME}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASS: ${APP_DB_PASS}
      APP_DB_SCHEMA: ${APP_DB_SCHEMA:-eda.}

      # Account Database
      ACCT_DB_TNS_NAME: ${ACCT_DB_TNS_NAME}
      ACCT_DB_USER: ${ACCT_DB_USER}
      ACCT_DB_PASS: ${ACCT_DB_PASS}

      # User Database
      USER_DB_TNS_NAME: ${USER_DB_TNS_NAME}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: ${USER_DB_PASS}
      USER_DB_SCHEMA: ${USER_DB_SCHEMA:-userlogins5}

      # Auth Secret (needed along with user/acct DBs for auth)
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}

  eda-merge:
    image: veupathdb/eda-merging:${MERGING_TAG:-latest}
    environment:
      # port providing the service
      SERVER_PORT: ${MERGING_SERVER_PORT:-8080}

      # URLs of required services
      SUBSETTING_SERVICE_URL: ${SUBSETTING_SERVICE_URL:-http://eda-subsetting}:${SUBSETTING_SERVER_PORT:-8080}

  eda-data:
    image: veupathdb/eda-data:${DATA_TAG:-latest}
    environment:
      # port providing the service
      SERVER_PORT: ${DATA_SERVER_PORT:-8080}

      # URLs of required services
      SUBSETTING_SERVICE_URL: ${SUBSETTING_SERVICE_URL:-http://eda-subsetting}:${SUBSETTING_SERVER_PORT:-8080}
      MERGING_SERVICE_URL: ${MERGING_SERVICE_URL:-http://eda-merge}:${MERGING_SERVER_PORT:-8080}
      RSERVE_URL: ${RSERVE_URL:-http://rserve:6311}
      DATASET_ACCESS_SERVICE_URL: ${DATASET_ACCESS_SERVICE_URL:-http://dataset-access}:${DATASET_ACCESS_SERVER_PORT:-8080}

      # LDAP values to look up DBs
      LDAP_SERVER: ${LDAP_SERVER}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN}

      # Account Database
      ACCT_DB_TNS_NAME: ${ACCT_DB_TNS_NAME}
      ACCT_DB_USER: ${ACCT_DB_USER}
      ACCT_DB_PASS: ${ACCT_DB_PASS}

      # User Database
      USER_DB_TNS_NAME: ${USER_DB_TNS_NAME}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: ${USER_DB_PASS}
      USER_DB_SCHEMA: ${USER_DB_SCHEMA:-userlogins5}

      # Auth Secret (needed along with user/acct DBs for auth)
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}

  eda-user:
    image: veupathdb/eda-user:${USER_TAG:-latest}
    environment:
      # port providing the service
      SERVER_PORT: ${USER_SERVER_PORT:-8080}

      # LDAP values to look up DBs
      LDAP_SERVER: ${LDAP_SERVER}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN}

      # Account Database
      ACCT_DB_TNS_NAME: ${ACCT_DB_TNS_NAME}
      ACCT_DB_USER: ${ACCT_DB_USER}
      ACCT_DB_PASS: ${ACCT_DB_PASS}

      # User Database
      USER_DB_TNS_NAME: ${USER_DB_TNS_NAME}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: ${USER_DB_PASS}
      USER_DB_SCHEMA: ${USER_DB_SCHEMA:-userlogins5}

      # Auth Secret (needed along with user/acct DBs for auth)
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}

      # Project-specific properties for user schema
      PROJECT_SPECIFIC_PROP_CE_PROJECT_ID: ClinEpiDB
      PROJECT_SPECIFIC_PROP_CE_USER_SCHEMA: edauserce

      PROJECT_SPECIFIC_PROP_ACE_PROJECT_ID: AllClinEpiDB
      PROJECT_SPECIFIC_PROP_ACE_USER_SCHEMA: edauserce

      PROJECT_SPECIFIC_PROP_MB_PROJECT_ID: MicrobiomeDB
      PROJECT_SPECIFIC_PROP_MB_USER_SCHEMA: edausermb

  dataset-access:
    image: veupathdb/dataset-access-service:${DAS_TAG:-latest}
    environment:
      # port providing the service
      SERVER_PORT: ${DATASET_ACCESS_SERVER_PORT:-8080}

      # LDAP values to look up DBs
      LDAP_SERVER: ${LDAP_SERVER}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN}

      # Application Database
      APP_DB_TNS_NAME: ${APP_DB_TNS_NAME}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASS: ${APP_DB_PASS}
      APP_DB_POOL_SIZE: 20

      # Account Database
      ACCT_DB_TNS_NAME: ${ACCT_DB_TNS_NAME}
      ACCT_DB_USER: ${ACCT_DB_USER}
      ACCT_DB_PASS: ${ACCT_DB_PASS}
      ACCT_DB_POOL_SIZE: 20

      # User Database
      USER_DB_TNS_NAME: ${USER_DB_TNS_NAME}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: ${USER_DB_PASS}
      USER_DB_SCHEMA: ${USER_DB_SCHEMA:-userlogins5}

      # Auth Secret (needed along with user/acct DBs for auth)
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}

      # Email Config
      SMTP_HOST: ${SMTP_HOST?required}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL?required}
      EMAIL_DEBUG: ${EMAIL_DEBUG:-false}

      # Web Client URLs
      SITE_URL: ${SITE_URL}                     # e.g. https://clinepidb.org/ce
      REGISTRATION_PATH: /app/user/registration # unused for now
      APPLICATION_PATH: /app/study-access       # unused for now

  eda-compute:
    build:
      dockerfile: Dockerfile
      context: ..
    ports:
    - "8080:8080"
    depends_on:
    - minio
    - queue
    - queue-db
    - dataset-access
    - eda-subsetting
    - eda-merge
    environment:
      # Auth Secret (needed along with user/acct DBs for auth)
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}

      # port providing the service
      SERVER_PORT: ${COMPUTE_SERVER_PORT:-8080}

      # LDAP values to look up DBs
      LDAP_SERVER: ${LDAP_SERVER}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN}

      # Application Database
      APP_DB_TNS_NAME: ${APP_DB_TNS_NAME}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASS: ${APP_DB_PASS}
      APP_DB_POOL_SIZE: 20

      # Account Database
      ACCT_DB_TNS_NAME: ${ACCT_DB_TNS_NAME}
      ACCT_DB_USER: ${ACCT_DB_USER}
      ACCT_DB_PASS: ${ACCT_DB_PASS}
      ACCT_DB_POOL_SIZE: 20

      # User Database
      USER_DB_TNS_NAME: ${USER_DB_TNS_NAME}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASS: ${USER_DB_PASS}
      USER_DB_SCHEMA: ${USER_DB_SCHEMA:-userlogins5}

      # Queue Platform Postgres
      QUEUE_DB_NAME: ${COMPUTE_POSTGRES_DB}
      QUEUE_DB_HOST: ${COMPUTE_POSTGRES_HOST}
      QUEUE_DB_PORT: ${COMPUTE_POSTGRES_PORT}
      QUEUE_DB_USERNAME: ${COMPUTE_POSTGRES_USER}
      QUEUE_DB_PASSWORD: ${COMPUTE_POSTGRES_PASS}
      QUEUE_DB_POOL_SIZE: ${COMPUTE_POSTGRES_POOL_SIZE}

      # Queue Platform RabbitMQ
      JOB_QUEUE_USERNAME: ${COMPUTE_QUEUE_USER}
      JOB_QUEUE_PASSWORD: ${COMPUTE_QUEUE_PASS}
      JOB_QUEUE_HOST: ${COMPUTE_QUEUE_HOST}
      JOB_QUEUE_PORT: ${COMPUTE_QUEUE_PORT}
      SLOW_QUEUE_NAME: ${COMPUTE_QUEUE_SLOW_NAME}
      SLOW_QUEUE_WORKERS: ${COMPUTE_QUEUE_SLOW_WORKERS}
      FAST_QUEUE_NAME: ${COMPUTE_QUEUE_FAST_NAME}
      FAST_QUEUE_WORKERS: ${COMPUTE_QUEUE_FAST_WORKERS}

      # Queue Platform Minio
      S3_HOST: ${COMPUTE_S3_HOST}
      S3_BUCKET: ${COMPUTE_S3_BUCKET}
      S3_ACCESS_TOKEN: ${COMPUTE_S3_ACCESS_TOKEN}
      S3_SECRET_KEY: ${COMPUTE_S3_SECRET_KEY}
      S3_PORT: ${COMPUTE_S3_PORT}

      # Job Settings
      JOB_CACHE_TIMEOUT_DAYS: 30

      # EDA Stack Settings
      EDA_SUBSETTING_HOST: ${SUBSETTING_SERVICE_URL:-http://eda-subsetting}:${SUBSETTING_SERVER_PORT:-8080}
      EDA_MERGE_HOST: ${MERGING_SERVICE_URL:-http://eda-merge}:${MERGING_SERVER_PORT:-8080}
      DATASET_ACCESS_HOST: ${DATASET_ACCESS_SERVICE_URL:-http://dataset-access}:${DATASET_ACCESS_SERVER_PORT:-8080}
      RSERVE_HOST: ${RSERVE_URL:-http://rserve:6311}