package org.veupathdb.service.eda.compute.plugins

import org.veupathdb.service.eda.generated.model.ComputeRequestBase

/**
 * Plugin Provider.
 *
 * Helper class that describes and assists in instantiating an instance of an
 * [AbstractPlugin] implementation.
 *
 * @param R HTTP request payload type.
 *
 * @param C Plugin configuration type.
 */
interface PluginProvider<R : ComputeRequestBase, C> {

  /**
   * URL Segment that identifies the specific plugin generated by this provider.
   */
  val urlSegment: String

  /**
   * Human friendly display name for the plugin generated by this provider.
   */
  val displayName: String

  /**
   * Optional human friendly description of the plugin generated by this
   * provider.
   */
  val description: String?
    get() = null

  /**
   * The class for the type of the HTTP request payload.
   *
   * This value is used to deserialize the request payload for use by the plugin
   * execution.
   */
  val requestClass: Class<R>

  /**
   * Creates a new instance of this plugin
   */
  fun getPlugin(request: R): AbstractPlugin<R, C>

  fun getValidator(): PluginConfigValidator<R>

}