#%RAML 1.0 Library

uses:
  eda: ../eda-common-lib.raml

types:
  AlphaDivPluginRequest:
    type: eda.ComputeRequestBase
    properties:
      config: AlphaDivPluginConfig

  AlphaDivPluginConfig:
    type: object
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      collectionVariable: VariableSpec
      alphaDivMethod: AlphaDivMethod

  AlphaDivMethod:
    type: string
    enum: ['shannon', 'simpson', 'evenness']
