#%RAML 1.0 Library

uses:
  eda: ../eda-common-lib.raml

types:
  BetaDivPluginRequest:
    type: eda.ComputeRequestBase
    properties:
      config: BetaDivPluginConfig

  BetaDivPluginConfig:
    type: object
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      collectionVariable: VariableSpec
      betaDivDistanceMethod: BetaDivDistanceMethod

  BetaDivDistanceMethod:
    type: string
    enum: ['bray', 'jaccard', 'jsd']
