#%RAML 1.0 Library

types:

  CorrelationPluginRequest:
    type: ComputeRequestBase
    properties:
      config: CorrelationComputeConfig

  CorrelationComputeConfig:
    properties:
      collectionVariable1: 
        type: CollectionSpec
        required: false
      collectionVariable2:
        type: CollectionSpec
        required: false
      correlationMethod: CorrelationMethod

  CorrelationMethod:
    type: string
    enum: ['spearman','pearson']

  CorrelationStatsResponse:
    properties: 
      data1: string[]
      data2: string[]
      correlationCoef: string[]
      pValue: 
        type: string[]
        required: false
      adjustedPValue: 
        type: string[]
        required: false
