#%RAML 1.0 Library

types:

  CorrelationMethod:
    type: string
    enum: ['spearman','pearson']

  SelfCorrelationMethod:
    type: string
    enum: ['spearman','pearson','sparcc']

  FeaturePrefilterThresholds:
    additionalProperties: false
    properties:
      proportionNonZero?: 
        type: number # should be between 0 and 1 inclusive
      variance?:
        type: number # should be 0 or greater
      standardDeviation?:
        type: number # should be 0 or greater

  BaseCorrelationComputeConfig:
    properties:
      prefilterThresholds?: FeaturePrefilterThresholds

  CorrelationInputDataTypes:
    type: string
    enum: ["metadata","collection"]

  # If metadata isn't a collection, then we shouldn't be forcing correlation to use collections
  # as the input. It should be an option of a data type.
  CorrelationInputData:
    properties: 
      dataType: CorrelationInputDataTypes
      collectionSpec?: CollectionSpec

  CorrelationConfig:
    type: BaseCorrelationComputeConfig
    properties: 
      correlationMethod: CorrelationMethod
      data1: CorrelationInputData
      data2: CorrelationInputData

  # if one collection is passed, assume the second thing is metadata
  CorrelationPluginRequest:
    type: ComputeRequestBase
    properties:
      config: CorrelationConfig

  SelfCorrelationConfig:
    type: BaseCorrelationComputeConfig
    properties:
      correlationMethod: SelfCorrelationMethod
      data1: CollectionSpec #someday if we do metadata X metadata, make this CorrelationInputData

  SelfCorrelationPluginRequest:
    type: ComputeRequestBase
    properties:
      config: SelfCorrelationConfig

  CorrelationStatsResponse:
    additionalProperties: false
    properties:
      statistics: CorrelationPoint[]
      data1Metadata: string
      data2Metadata: string

  CorrelationPoint:
    properties: 
      data1: string
      data2: string
      correlationCoef: 
        type: string
        required: false
      pValue: 
        type: string
        required: false
      adjustedPValue:
        type: string
        required: false

