#%RAML 1.0 Library

types:

  DifferentialAbundancePluginRequest:
    type: ComputeRequestBase
    properties:
      config: DifferentialAbundanceComputeConfig

  DifferentialAbundanceComputeConfig:
    properties:
      collectionVariable: VariableSpec
      comparator: ComparatorSpec
      differentialAbundanceMethod: DifferentialAbundanceMethod

  DifferentialAbundanceMethod:
    type: string
    enum: ['DESeq','ANCOMBC']

  ComparatorSpec:
    type: object
    properties:
      variable: VariableSpec
      groupA: BinRange[]
      groupB: BinRange[]

  DifferentialAbundanceStatsResponse:
    properties:
      log2foldChange: string[]
      pValue: string[]
      adjustedPValue: string[]
      pointId: string[]

# Not the same as LabeledRange from EdaCommon
# Taken from data service (should move to common)
  BinRange:
    additionalProperties: false
    properties:
      binStart: string
      binEnd: string
      binLabel: string