#%RAML 1.0 Library

types:
  ExamplePluginRequest:
    type: ComputeRequestBase
    properties:
      config: ExamplePluginConfig

  ExamplePluginConfig:
    type: object
    properties:
      outputEntityId: string
      inputVariable: VariableSpec
      valueSuffix: string
