#%RAML 1.0 Library

uses:
  eda: ../eda-common-lib.raml

types:
  ExamplePluginRequest:
    type: eda.ComputeRequestBase
    properties:
      config: ExamplePluginConfig

  ExamplePluginConfig:
    type: object
    properties:
      outputEntityId: string
      inputVariable: eda.VariableSpec
      valueSuffix: string
