#%RAML 1.0 Library

types:
  RankedAbundancePluginRequest:
    type: ComputeRequestBase
    properties:
      config: RankedAbundancePluginConfig

  RankedAbundancePluginConfig:
    type: object
    additionalProperties: false
    properties:
      outputEntityId:
        type: string
      collectionVariable: VariableSpec
      rankingMethod: RankingMethod

  RankingMethod:
    type: string
    enum: ['median', 'q3', 'variance', 'max']
