#%RAML 1.0 Library

uses:
  eda: ../eda-common-lib.raml

types:
  ComputeRequestBase:
    type: object
    properties:
      studyId:
        type: string
      filters:
        type: array
        items:
          type: eda.API_Filter
        required: false
      derivedVariables:
        type: array
        items:
          type: eda.DerivedVariable
      config:
        # Stand-in property just to have the methods present on the parent type
        # in java.  This field is to be overridden by specific plugin request
        # types.
        type: object
    additionalProperties: false

  # TODO: remove this.  It's just a dummy type showing you can override properties defined on parent types.
  ComputeRequestExtension:
    type: ComputeRequestBase
    properties:
      config:
        type: ExampleComputeConfig

  # TODO: remove this
  ExampleComputeConfig:
    type: object
    properties:
      foo:
        type: string
